### ISSUE TITLE
Which FPKI Certs on a PIV Should be Used for What Purpose

### ISSUE THREAD

**Issue by weirdscience** [GSA/piv-guides#101]
#### Description of Issue: ####
It is difficult to understand which certs should be used for which purpose. For example, which PIV cert should be used for client auth versus which should be used to sign stuff. How do I tell the difference and how do I make sure I am issued the correct certificates? What if I do not have the right certificate?

#### Details of Issue: ####
See above.

#### References (Docs, Links, Files): ####
No references.

#### If a New Page or Content is Needed, Expected Outcomes: ####
New page with the following:

1. a table aligning all FPKI certificates with its intended purpose.
2. a guide on how to identify each certificate.
3. Little harder, what to do if the intended certificate does not have the appropriate extensions.

#### Link to the Content Page for Contributors: ####
None

#### Adding Related Request from FPKI-Guides' Issue #159 - "Distinguishing between certs on a PIV" 

**Note: PIV-Guides location more applicable.  FPKI-Guides' Issue #159 now closed.**

- Posted by woodyweaver on December 12, 2017

#### Description of Issue: ####
Users (and engineers) often don't understand the differences between the auth and digital signature cert. It would be helpful to expand on the explanation from a functional and programmatic perspective.

#### Details of Issue: ####
A useful application would be to force use of the auth cert rather than the digital signature cert when performing client authentication (e.g. SSL client auth.) For a PIV, this can be achieved by checking for 2.16.840.1.101.3.2.1.3.13. However, if the application needs to interoperate with the DoD environment, this OID may or may not be present (it looks like the DoD SHA2 CAC asserts the Common Auth OID, but others don't.)

Recommendations on how to achieve that distinction programmatically across the entirety of the Federal bridge would be welcome.

**No additional comments were posted to FPKI-Guide Issue #159.**

**Comment by lachellel** [comment]
> a table aligning all FPKI certificates with its intended purpose.

- Not for all FPKI certificates - but specific to PIV: 
- https://piv.idmanagement.gov/details/#understanding-piv-certificates

> a guide on how to identify each certificate.

- might want to break out the [details](https://piv.idmanagement.gov/details/) into smaller chunks of information and side nav

> Little harder, what to do if the intended certificate does not have the appropriate extensions.

- this is a compliance issue and generally the intended audience for this playbook isn't involved in compliance - they are trying to make something "work"
- we can move this one elsewhere or create a compliance focused link

**Comment by rt-smithee** [comment]
IMO it should say "SHA-256" not "SHA-2" because SHA-2 is a hash family including e.g. SHA-384, SHA-512, SHA-224, etc.

**Comment by godadada** [comment]
https://ocio.nih.gov/Smartcard/Pages/Your-PIV-Certificates.aspx#TYPE

Types of Certificates on your PIV card
Your PIV card contains four types of digital certificates:
Authentication Certificate used to log you on to applications and computers. 
This certificate usually has an -A after your name.
Encryption Certificate used to encrypted email messages send to you. 
This certificate usually has an -E after your name.
Signing Certificate used to digatally sign emails and documents. 
This certificate usually has an -S after your name.
Card Management Certificate which is not currently used at NIH. 
This certificate is issued to PIV or PIV Users.
The new 128K PIV Cards (see below) may also contain up to five of your prior encryption certificates to make it easier for you to read old encrypted emails. These certificates will have older expiration dates and may, or may not, have an -E after your name.

Note: If you have a 64K PIV card, or need to read very old encrypted emails, you will need to recover the old certificates and associated keys used to encrypt them.

**Comment by godadada** [comment]
commited: 
https://github.com/GSA/piv-guides/blob/piv-cert-typs/pages/piv-certificate-types.md

**Comment by clstmbrly** [comment]
Putting on hold, per @lachellel on 8/29/2017.

**Comment by clstmbrly** [comment]
This Issue is very similar to FPKI-Guides' Issue [#159](https://github.com/GSA/fpki-guides/issues/159), "Distinguishing between certs on a PIV." Combined request from FPKI-Guides' #159 with PIV-Guides' #101--more applicable location.  FPKI-Guides' #159 is now closed.
@ryancdickson

**Comment by maxwellfunk** [comment]
due to lack of consistency across all PIV issuers in adding suffixes to the common names (-A, -E, -S) the only way to distinguish certs by profile is a combination of KU and EKU which is accounted or in the table of the following page:
https://piv.idmanagement.gov/details/#understanding-piv-certificates
