### ISSUE TITLE
SHA-1 References

### ISSUE THREAD

**Issue by rsgmodelworks** [GSA/piv-guides#104]
Page "Identifiers in a PIV Credential" references SHA-1

Perhaps should reference SHA-256 instead. 

#### If a New Page or Content is Needed, Expected Outcomes: ####

https://piv.idmanagement.gov/identifiers/

**Comment by lachellel** [comment]
That identifier is the Thumbprint.  It's a **computed** value (can be sha-1, md5, sha-256, etc) and not related to the signing algorithms associated with the certificate itself.

The SHA-1 Thumbprints (**computed** identifiers) are used in OCSP, querying against certificate stores in most operating systems, and account linking (as an option) for network authentication using MS AD. 

Related to #47 and adding clarity between the identifiers (generic) and the account linking (specific to network authentication).
