### ISSUE TITLE
Anchor links varying behavior

### ISSUE THREAD

**Issue by djpackham** [GSA/piv-guides#110]
#### Description of Issue: ####
It seems that there may need to be an HTML / CSS edit to make the content display correctly when clicking on anchor links. It seems like the beginning of the content that is being referenced from the anchor link is getting caught behind the header of the page.

#### Details of Issue: ####
I am seeing varying results when I click on anchor links. If a do a hard refresh (ctrl + f5) the page displays the expected content. However, clicking on anchor links without hard refreshes seems to be hiding the beginning of the expected content behind the header.

At least I've noticed this behavior on IE 11 and Chrome Version 58.0.3029.81

**Comment by maxwellfunk** [comment]
closing, works properly on new playbooks site as well as the old; currently it moves you down to the top of each clickable header.
