### ISSUE TITLE
Consistency of Template.md pages

### ISSUE THREAD

**Issue by clstmbrly** [GSA/piv-guides#130]
#### Description of Issue: ####
The content contained in the Template.md pages (and their locations in the directory structures) is not consistent across the PIV-Guides, FPKI-Guides, and FICAM-Arch repos.

#### Details of Issue: ####
1.	The Template.md pages provide style and general instructions for those who need to write guides or information for the PIV-Guides, FPKI-Guides, and FICAM-Arch. 
2.	The content contained in the Template.md pages is not consistent across the 3 repos.  
3.	The Template.md pages are not located at the same directory structure level for all 3 repos. 

#### References (Docs, Links, Files): ####
https://github.com/GSA/piv-guides/blob/staging/pages/template.md
https://github.com/GSA/fpki-guides/blob/staging/template.md
https://github.com/GSA/fpki-guides/blob/staging/pages/template.md
https://github.com/GSA/ficam-arch/blob/staging/template.md

#### If a New Page or Content is Needed, Expected Outcomes: ####
1.	Make the content consistent for all Template.md pages:  sample outline for guides, the same style and general instructions, and Markdown syntax (style sheet).
2.	Place all Template.md pages in a consistent location in the directory structures for all 3 repos.

#### Link to the Content Page for Contributors: ####
None.

**Comment by lachellel** [comment]
files have been merged in this repo
Same files and changes can be applied to the other repos

**Comment by clstmbrly** [comment]
Found CONTRIBUTING.md is in top level of Repo.  This is an older version of the new contribute files in the Pages folder and should be removed.  Would you like me to remove this file (if I have access to Staging)?

**Comment by lachellel** [comment]
No - please do not remove.
 
The CONTRIBUTING.md is part of the github repo - when a user submits a pull request, that file is displayed and contains the _terms and conditions_ that they are agreeing to by submitting a change (agreeing to open source licensing, open community, no marketing, plain language, etc). 

- https://help.github.com/articles/setting-guidelines-for-repository-contributors/

We can modify the CONTRIBUTING.md to update everything after "how to contribute" and link to the contribute page.

**Comment by clstmbrly** [comment]
Understood.  Thanks very much.

**Comment by clstmbrly** [comment]
“Open an Issue” is briefly described in **contribute.md**, but more details are given in **contribute_openissue.md**.
The **contribute_openissue.md** in the 3 Repos was last updated in March. 
Do you want to keep this file?
The FPKI-Guides’ contribute_openissue.md is the best (most concise) version.
If you want to keep this file, recommend that I replicate the FPKI-Guides’ version to PIV-Guides and FICAM-Arch (and not the other way around).

**Comment by lachellel** [comment]
+1
if you think the fpki contribute_openissue.md is better, replicate / overwrite the file in the other two.

**Comment by clstmbrly** [comment]
Will do.  Thanks a bunch.

**Comment by lachellel** [comment]
merged and pushed to site
closing
thank you
