### ISSUE TITLE
Kramdown does not support nested

### ISSUE THREAD

**Issue by godadada** [GSA/piv-guides#144]
#### Description of Issue: ####
ordered nested lists do not work

#### Details of Issue: ####
following nested lists does not work:

1. list item 1
     1. sub list item 1
      2. sub list item 2
2. list item 2

following nested lists does not work:

1. list item 1
     * sub list item 1
     * sub list item 2
2. list item 2

**Comment by lachellel** [comment]
I'm fine with simplifying.  Using nested makes rendering on mobile (etc) difficult for users to read in some cases.  

We simplified previous markdown to not use nested.  I don't think we need to use nested and can organize differently.
