### ISSUE TITLE
Need to change css file to make empty lines in Kramdown files

### ISSUE THREAD

**Issue by godadada** [GSA/piv-guides#145]
#### Description of Issue: ####
Kramdown does not show needed empty line sometimes

#### Details of Issue: ####
Some of the playbooks, empty ssh-all.md, 2b_domaincontrollers.md, 2a_domaincontrollers.md
are crammed without needed empty lines between section. CSS file modification is needed to create the new lines.

#### References (Docs, Links, Files): ####
ssh-all.md, 2b_domaincontrollers.md, 2a_domaincontrollers.md

**Comment by maxwellfunk** [comment]
closing prior to migration to new playbooks site.
