### ISSUE TITLE
Playbook to configure Firefox and PIV login

### ISSUE THREAD

**Issue by godadada** [GSA/piv-guides#148]
#### Description of Issue: ####

Need playbook to configure Firefox and use PIV to login certain web site.
#### References (Docs, Links, Files): ####
resources:
https://github.com/OpenSC/OpenSC/releases
https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step
https://github.com/OpenSC/OpenSC/issues/1031

related issue:
https://github.com/GSA/piv-guides/issues/20

**Comment by clstmbrly** [comment]
The Firefox write-up gives only 2 steps. These provide links to go elsewhere for the procedures.

Does this give the user enough detail or should it be expanded?

**Comment by lachellel** [comment]
It doesn't give any context as-is.  We need to add the Govt / Federal context...why are you doing this?  What is being solved? When would you do this?  What is the underlying problem?

**Comment by indrajit-gsa** [comment]
Are we going to rely on an external link for instructions on this? Should we have alternate solutions?

**Comment by indrajit-gsa** [comment]
@lachellel @djpackham 
The new markdown is located here for review - https://github.com/GSA/piv-guides/blob/firefox/_userconfig/1_firefox.md
I also added an option on GFE that enables kerberos auth in Firefox, which is probably the case for many agencies.

**Comment by clstmbrly** [comment]
BTW, this is a 1st draft of the rewritten Firefox write-up.  It hasn't been edited yet.

**Comment by indrajit-gsa** [comment]
Based on the feedback, I removed the GFE option for kerberos authentication (SPNEGO).

**Comment by clstmbrly** [comment]
@lachellel @djpackham  I have 2 questions about the Playbook and would appreciate your direction/thoughts:
1)	I'm concerned that the linked steps [https://github.com/OpenSC/OpenSC/wiki] needed to download, install, and test OpenSC seem too technically advanced for a general user. To test the install, the user would need to know how to launch the OS command prompt and use the command language, as well as have a deeper knowledge about file types and directories. To address this in the Playbook, I said: “To test the install, you will need to use the OS command prompt. If you haven't done this before, ask your system administrator or help desk for assistance.”  Does this work?  Any other suggestions?

2)	Can we reference a commercial Firefox-CAC solution for DoD personnel (i.e., not “vendor-neutral,” per Contributing.md)? It “may be” free to DoD folks.  I could not confirm this from the website:  [https://militarycac.com/activclientalternate.htm].  The text is currently in an "info-alert" box.

Thanks very much:-)

**Comment by lachellel** [comment]
fixed in #181 and #185

**Comment by lachellel** [comment]
open new issues for additions and changes!
