### ISSUE TITLE
Addition of Authentication Mechanism Assurance

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#16]
Add the Authentication Mechanism Assurance to the network enablement as an advanced topic:
- http://csrc.nist.gov/groups/SNS/piv/fips_201-2_march_2015/day_two/tim_baldrige_ad_fips201-2_2015.pdf

@twbaldridge has also provided public domain scripts as samples for engineers to use.

**Comment by lachellel** [comment]
Registry Setting: 

- [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\kdc]
- "ChainWithIssuancePolicyOIDs"=dword:00000001


KDC Patch: the patch to correct the KDC not setting the certificate issuance policy when the KDC validates the smartcard certificate 
  - http://support.microsoft.com/kb/2771254


Script to set the Certificate OIDs on the domain: 

- [CertificateIssuanceOIDs.ps1.txt](https://github.com/GSA/piv-guides/files/621976/CertificateIssuanceOIDs.ps1.txt)

**Comment by godadada** [comment]
What are the server version assumptions for the target Windows servers, e.g. Windows Svr 2008 R2 and above or Windows Svr 20012 and above?


Thanks
Chunde

**Comment by godadada** [comment]
Authentication Mechanism Assurance### • Authentication mechanism assurance is an added capability in### Windows Server 2008 R2 AD DS that you can use when the domain### functional level is set to Windows Server 2008 R2. When it is enabled,### authentication mechanism assurance adds an administrator-designated### global group membership to a user’s Kerberos token when the user’s### credentials are authenticated during logon using a certificate-based### logon method

### • Authentication Mechanism Assurance (AMA)  for AD DS in Windows### Server 2008 R2

## • https://technet.microsoft.com/en-us/library/dd378897(v=WS.10).aspx### • Power Shell Script for Common Federal/DoD Certificate Policies### simplifies implementation as compared to TechNet Step-by-Step Guide.



Authentication Mechanism Assurance• The Windows Server® 2008 R2 patch to correct theKDC not setting the certificate issuance policy whenthe KDC validates the smartcard certificate is nowavailable via the following link.

• http://support.microsoft.com/kb/2771254• Windows Server® 2012 and after -- no patch required• Enable AMA Priority above  Most Recently IssuedSuperior Certificate Heuristic with the following### • Windows Registry Editor Version 5.00

**Comment by godadada** [comment]
I need to decide where to put the script https://github.com/GSA/piv-guides/files/621976/CertificateIssuanceOIDs.ps1.txt in FICAM-scripts repo.

**Comment by clstmbrly** [comment]
Question about Certificate Policies referencing:  is it okay to refer to them in this "shorthand" way (below) for a Playbook and not spell out the full titles (as with more formal documents)?

* This Power Shell Script for the Federal Common and DoD Certificate Policies simplifies the Microsoft TechNet steps for the Windows Server 2012: 
   
    https://github.com/GSA/piv-guides/files/621976/CertificateIssuanceOIDs.ps1.txt

Thanks very much.

**Comment by clstmbrly** [comment]
@lachellel @djpackham The AMA Playbook is ready for your review. Please let us know if you have comments and/or changes.  Thank you. 

https://github.com/GSA/piv-guides/blob/auth-mech-assurance/_networkconfig/10_AMA.md

**Comment by indrajit-gsa** [comment]
@lachellel
Here are the policies in 3 categories that are recommended for logon via AMA. Appreciate your feedback. There is one DOD policy. Do we need treasury and Dept of State policies?

# Common
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.3.7 id-fpki-common-hardware
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.3.13 id-fpki-common-authentication
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.3.16 id-fpki-common-high
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.3.40 id-fpki-common-derived-pivAuth
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.3.41 id-fpki-common-derived-pivAuth-hardware

# PIV-I hardware
set-ADUG-CertIssOID 1.3.6.1.4.1.3922.1.1.1.18 WidePoint-ORC
set-ADUG-CertIssOID 1.3.6.1.4.1.23337.1.1.10 Verizon
set-ADUG-CertIssOID 1.3.6.1.4.1.23337.1.1.8 Verizon
set-ADUG-CertIssOID 1.3.6.1.4.1.45606.3.1.20 CertiPath-Bridge-member
set-ADUG-CertIssOID 1.3.6.1.4.1.25054.3.1.20 Carillon-PIV-I-provider
set-ADUG-CertIssOID 1.3.6.1.4.1.16334.509.2.9 CertiPath Bridge-member-Northrop-Grumman-(enterprise-PKI)
set-ADUG-CertIssOID 1.3.6.1.4.1.47951.2.2.5.7 STRAC-Bridge-member-Foundation-for-Trusted-Identity
set-ADUG-CertIssOID 1.3.6.1.4.1.45606.3.1.20 TSCP-Bridge-member-Carillon
set-ADUG-CertIssOID 1.3.6.1.4.1.38948.2.1.2.7 TSCP-Bridge-member-SureID
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.12.6 id-eca-medium-hardware-pivi
set-ADUG-CertIssOID 2.16.840.1.114027.200.3.10.7.6 Entrust
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.18.0 id-identrust-IGC-PIV-I-Hardware-Identity
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.18.1 Identrust-IGC-PIV-I-Hardware-Signing
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.18.2 Identrust-IGC-PIV-I-Hardware-Encryption
set-ADUG-CertIssOID 2.16.840.1.113733.1.7.23.3.1.18 Symantec

# Medium Hardware
set-ADUG-CertIssOID 1.2.6.1.4.1.73.15.3.1.12 The-Boeing-Company-(CertiPath)
set-ADUG-CertIssOID 1.3.6.1.4.1.25054.3.1.12 Carillon-(CertiPath)
set-ADUG-CertIssOID 1.3.6.1.4.1.45606.3.1.12 id-mediumHardware-256
set-ADUG-CertIssOID 1.3.6.1.4.1.103.100.1.1.3.3 Lockheed-Martin-(CertiPath)
set-ADUG-CertIssOID 1.3.6.1.4.1.16334.509.2.8 Northrop-Grumman-(CertiPath)
set-ADUG-CertIssOID 1.3.6.1.4.1.1569.10.1.11 Raytheon-Company-(CertiPath)
set-ADUG-CertIssOID 1.3.6.1.4.1.1569.10.1.12 Raytheon-Company-(CertiPath)
set-ADUG-CertIssOID 1.3.6.1.4.1.45606.3.1.12 Carillon-(TSCP)
set-ADUG-CertIssOID 1.3.6.1.4.1.103.100.1.1.3.3 Lockheed-Martin-(TSCP)
set-ADUG-CertIssOID 1.3.6.1.4.1.38948.2.1.2.2 SureID-(TSCP)
set-ADUG-CertIssOID 1.3.6.1.4.1.13948.1.1.1.6 Exostar
set-ADUG-CertIssOID 1.3.6.1.4.1.3922.1.1.1.12 id-orc-nfissp-mediumhardware
set-ADUG-CertIssOID 1.3.6.1.4.1.47951.2.2.5.4 Foundation-for-Trusted-Identity-(STRAC)
set-ADUG-CertIssOID 2.16.840.1.113733.1.7.23.3.1.7 Symantec
set-ADUG-CertIssOID 2.16.840.1.101.2.1.11.42 id-US-dodmediumHardware-112
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.2.9 id-pto-mediumHardware
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.12.5 id-eca-medium-token-sha256
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.12.10 id-eca-medium-hardware-sha256
set-ADUG-CertIssOID 2.16.840.1.101.3.2.1.17.2 id-gpo-medium-hardware
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.12.1 IdenTrust-Identity
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.12.2 IdenTrust-Signing
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.12.3 IdenTrust-Encryption
set-ADUG-CertIssOID 2.16.840.1.113839.0.100.12.4 IdenTrust
set-ADUG-CertIssOID 2.16.840.1.114027.200.3.10.7.2 Entrust
set-ADUG-CertIssOID 2.16.840.1.114027.200.3.10.7.4 Entrust

**Comment by indrajit-gsa** [comment]
This playbook will have a content with link to the script file. The ficam-scripts location has to be published as well. If not, is there any other place to host the scripts?

**Comment by indrajit-gsa** [comment]
@clstmbrly Hi Celeste, I have updated these documents for this playbook in the auth-mech-assurance branch for your review. I added some context for when to use AMA for government purposes. The script has been updated with the list of policies that was reviewed with the team. Please review for editorial.

https://github.com/GSA/piv-guides/blob/auth-mech-assurance/_networkconfig/10_AMA.md
https://github.com/GSA/ficam-scripts/tree/auth-mech-assurance/_AMA

**Comment by clstmbrly** [comment]
@lachellel AMA is ready for your review: [https://github.com/GSA/piv-guides/blob/auth-mech-assurance/_networkconfig/10_AMA.md](url).  Have a good evening:-).

**Comment by indrajit-gsa** [comment]
Adding the preview link for AMA write-up -- https://federalist-proxy.app.cloud.gov/preview/gsa/piv-guides/auth-mech-assurance/networkconfig/ama/

**Comment by lachellel** [comment]
authentication assurance was merged.  closing.
