### ISSUE TITLE
Filtering certs during browser auth 

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#18]
Add information and scripts that can be applied to filter the certificates presented to a user during browser-based client auth (PIV cert auth). 

This is a combination of browser settings and OS settings - dependent upon the CSP (crypto service provider) in use.  The filtering of certificates based on EKU values can help reduce confusion on which certificate to choose.  

Need to verify and validate if settings are available in all platforms and versions: 
- IE
- Edge
- Chrome
- Firefox
- Safari
- MacOSX
- Windows 7, 10

**Comment by lachellel** [comment]
@jimwalker53

**Comment by jimwalker53** [comment]
Here's a doc that my team pulled together addressing this for Windows 7/ Server 2008 R2.   I haven't had time to test this on Chrome or Edge.   I can work on that here in the next couple of days.   I don't have access to Safari/MaxOSX/Windows 10 so we'll have to depend on someone else to provide that info.

Please let me know if there are any questions!

[Enhancing the PIV Authentication Experience (Version 5).pdf](https://github.com/GSA/piv-guides/files/240648/Enhancing.the.PIV.Authentication.Experience.Version.5.pdf)

**Comment by lachellel** [comment]
@twbaldridge @paulSD

Would you happen to know where these settings moved to in Edge browser / Windows 10? 

- HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl
- DWORD key of “FEATURE_CLIENTAUTHCERTFILTER


Inquiring minds want to know.  I'm looking in the registry and articles, but if you've run into this already - would you mind posting a quick note so we can document / highlight?

**Comment by PaulSD** [comment]
Sorry, no, I don't happen to know where these settings moved to.  We don't have direct control over any client endpoints, so we don't keep track of these settings.  We basically just assume that users are using the default settings, and attempt to handle incorrect cert selections as best we can.

I'm still hoping to some day convince the FPKI to change the KeyUsage value listed in the cert profiles for Signature certs to fix this once and for all.  Some people still argue that the current KeyUsage value is intentionally permissive to ensure that all software can use the Signature certs when necessary, and that the proper KeyUsage value (as used by the browsers and most other software to properly distinguish between Auth and Signature certs) might limit the ability to use the Signature certs if some software happens to handle that specific KeyUsage value improperly.  However, this clearly leads to widespread user confusion in the most common use cases, and forces administrators to use ugly hacks like the above on a large scale to filter out improperly displayed Signature certificates.  There can't possibly be enough broken software (that fails to correctly identify Signature certs with the proper KeyUsage value) to justify the disasters created by using the same KeyUsage value for Auth and Signature certs...  I wonder if we can come up with some realistic numbers as to what the current KeyUsage setting is costing the government?

**Comment by maxwellfunk** [comment]
As bots and other automated solutions become prevalent it will still be necessary for them to express KU of digital signature and EKU of client authentication in order to be presented with a credential tile selection screen when accessing certain mutual TLS enabled web applications.

Most recent profiles do still allow client auth in the signature certificate EKU, but I think that would be the most feasible way of resolving this for PIV users.... outside of what some agencies have adopted in terms of adding usage suffixes to common names (-A, -S, -E).
