### ISSUE TITLE
Importing intermediate CA certs into NSS

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#20]
PIV Auth via browser - specific for managed enterprise devices
- Firefox browsers in use
- NSS needs to be updated using non-manual (no user intervention) methods by enterprise engineers
- Some of the intermediate CAs in the FPKI stop the CA name at OU rather than using a CN
- Do full chains for client (user) provided certificates need to be configured in the client for two-way TLS to succeed?  

certutil or other methods to manage _enterprise_ configurations for NSS

**Comment by godadada** [comment]
The following link seems to have detailed steps to resolve this issue:
    https://mbrownnyc.wordpress.com/2013/06/04/leverage-group-policy-to-manage-certificates-in-users-firefox-certificate-store/

It needs to be verified, tested on or modified for  Windows 64 bit systems

**Comment by godadada** [comment]
usefull link for record keeping:

https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step

**Comment by lachellel** [comment]
I don't think this is related to opensc.  This was a question on the listserves in 2016: 

https://listserv.gsa.gov/cgi-bin/wa.exe?A2=ICAM-COMMUNITY-TECH;b11ee856.1603

**Comment by godadada** [comment]
@lachellel 

I logged in to the linked site but got "unauthorized" response.

**Comment by godadada** [comment]
This link may help settle the issue of missing CN.

According to the link which reasoned from certificate standards like X509 etc, cert must have at least one of  cn or subjectAltName to be compliant. The said Entrust certs do not have CN, but I do not see subjectAltName neither, so they are not compliant. Also firefox is able to use subjectAltname if cn is not present.
https://groups.google.com/a/chromium.org/forum/m/#!topic/security-dev/IGT2fLJrAeo

**Comment by lachellel** [comment]
@godadada 

- The CN and SAN discussion is for _serverAuth_ end entity certs. 

 - The issue is on **intermediates** in federal pki and how some may not have CN, and loading those into nss when deploying into a federal enterprise as needed - for trust store management, building paths, etc.

**Comment by godadada** [comment]
firefox CA cert install:
https://github.com/christian-korneck/firefox_add-certs

**Comment by godadada** [comment]
NSS certutil.exe -n option specifies a nickname, which does not have to be cn. It could be any identifiable phrase associated with the cert, e.g. descriptive phrase for human reading convenience as long as it is distinct from other installed certs in the cert store. Therefore, some CA certs without CN in DN can still be installed into NSS cert store and works fine. I have tested following cases: install a CA cert without CN successfully into NSS cert store; also successfully PIV login to firefox with a test cert that issuer CA cert has only CN in DN ( I was not able to test a PIV cert with issuer CA cert that does not have CN in DN, but my test covers imcomplete DN in general).

**Comment by indrajit-gsa** [comment]
@lachellel 

Based on our discussion yesterday, should I remove the first section where it applies for Firefox supporting Windows Certificate Store? Also was this intended for non-windows OS as well?

https://github.com/GSA/piv-guides/blob/nss/_userconfig/1_nss.md

**Comment by ryancdickson** [comment]
Not sure where this stands currently, but I can (hopefully) help, if needed.

In the past, I've written bash scripts that import [N] number of certificates from a source directory into a target NSS DB via certutil. Nicknames for the add activity were derived by parsing the DNs of the certificates in the source directory. If this approach was used, administrators would just need to populate the source directory full of trusted certificates, and then run the script to import --- no intervention required (e.g., changing the script we post).

I did the above in Linux, but I have a feeling translating to a batch file or something more Windows friendly wouldn't be too bad.

**Comment by idmken** [comment]
This seems specific to PIV auth on Firefox which is addressed here https://piv.idmanagement.gov/engineering/firefox/
