### ISSUE TITLE
Redcloth vulnerability

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/piv-guides#201]
#### Description of Issue: ####
There is a [RedCloth vulnerability](https://github.com/GSA/piv-guides/network/dependencies#4223002) raised by Github based on the RedCloth version that is specified in the Gemfile.lock for this repo. 

#### Details of Issue: ####
The redcloth dependency will need to be evaluated and compared to the other repositories. If the RedCloth dependency is removed, it seems to render fine except one markdown file /_networkconfig/91_localca.md. Other repositories such as fpki-guides, ficam-arch etc. used by GSA FICAM does not seem to use the RedCloth module.

#### References (Docs, Links, Files): ####
https://github.com/GSA/piv-guides/network/dependencies#4223002

#### If a New Page or Content is Needed, Expected Outcomes: ####
N/A

#### Link to the Content Page for Contributors: ####
N/A

**Comment by clstmbrly** [comment]
This issue was moved to "Done" on 3/21/2018.  Closing issue.
@djpackham - If you disagree, please let me know.  
@ryancdickson
