### ISSUE TITLE
Steps for Digital Signing in MS Word

### ISSUE THREAD

**Issue by djpackham** [GSA/piv-guides#203]
#### Description of Issue: ####
Received a request from an agency to provide guides for digitally signing with a PIV credential in MS Word.

#### Details of Issue: ####
- Provide procedures for digitally signing with a PIV credential in the supported versions of MS Word
- Supported versions include MS Word 2010+
- Need to research if digital signing with a PIV credential is possible using O365 cloud version of Word
- Need to highlight how to configure hash algorithm settings.
  - I believe MS Word defaults to SHA-1 unless the network has a GPO that sets Microsoft products to use something else.

#### If a New Page or Content is Needed, Expected Outcomes: ####
- Look into creating a new "User Guides" section on the side nav
- Create a new page that includes steps for signing in the various supported versions of MS Word
- Look into creating screen capture videos

**Comment by indrajit-gsa** [comment]
@djpackham @clstmbrly -- I checked in the initial version of the user guide. It will build soon. Here is the preview link - https://federalist-proxy.app.cloud.gov/preview/gsa/piv-guides/203-signing/userguides/

**Comment by clstmbrly** [comment]
@djpackham For tracking and possible updating, it seems we should have a different Issue for the **new** Digitally Signing for MS Word - OFR, since we have 2 separate Playbooks. We can close it as needed.  Okay to create?

**Comment by lachellel** [comment]
@djpackham is this one closed?

**Comment by clstmbrly** [comment]
This Issue is not closed.  OFR sent us new updates to the "Digitally Signing in MS Word for OFR" Playbook. Perhaps this should have been a separate Issue.  Started making updates on 6/6/2018.

**Comment by clstmbrly** [comment]
The "Digitally Signing in MS Word for OFR" Playbook was published on 7/17/2018.

**Comment by clstmbrly** [comment]
@djpackham Should we leave this issue open (PIV #201, Steps for Digitally Signing in MS Word) for possible future OFR updates, etc.?  Also, some items (e.g., O365, SHA-1) were not addressed in the two published Playbooks.  

Alternatively, I could close this and open a new issue with just the remaining items. Thoughts?
@ryancdickson

**Comment by idmken** [comment]
Published here - https://piv.idmanagement.gov/userguides/signworddoc/

and here - https://piv.idmanagement.gov/userguides/signworddoc-ofr/
