### ISSUE TITLE
Add Search Box To PIV Guides

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/piv-guides#207]
#### Description of Issue: ####
There is no search feature in the PIV Guides.

#### Details of Issue: ####
Add a search box to PIV Guides and post the data to search.usa.gov. The feature will be similar to the one provided at idmanagement.gov.

#### References (Docs, Links, Files): ####
Should be added to the navbar.html and it will be included in all pages. Possibly replace the "View this site's code" button on the top navigation.

#### If a New Page or Content is Needed, Expected Outcomes: ####
New search box in PIV Guides website.

**Comment by weirdscience** [comment]
In researching RSS feed, Federalist recommends using Search.gov. Search.gov integration may help create individual Atom feeds per page.

https://search.usa.gov/signup
https://federalist.18f.gov/documentation/search/

**Comment by lachellel** [comment]
@weirdscience 

I have search functionality in a branch already (https://github.com/GSA/piv-guides/tree/addsearch).
