### ISSUE TITLE
Update network retrieval and timeout settings for Microsoft domains

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#224]
#### Description of Issue: ####
The current tuning configs link to 2008 / Win 7

#### Details of Issue: ####
Needs to be verified and updated for 2016 + 10

#### Link to the Content Page for Contributors: ####
https://piv.idmanagement.gov/networkconfig/tuning/

**Comment by maxwellfunk** [comment]
The tuning instructions were specific to CRL processing times for 2008, that section has since been removed now that it is no longer within its support lifetime.
