### ISSUE TITLE
Need script for AD to update EDIPI UPN field with PIV UPN

### ISSUE THREAD

**Issue by richtbenson** [GSA/piv-guides#238]
#### Description of Issue: ####
Currently in need of a PowerShell script for Active Directory to update (read) current users EDIPI (10 digit@mil) UPN field with PIV UPN (16Digit@mil).

#### Details of Issue: ####
OPORD related NAVADMIN

**Comment by maxwellfunk** [comment]
Closing as this is more of a DoD specific issue.  For context the first 10 digits of the UPN of a CAC authentication certificate is the internal EDIPI.
