### ISSUE TITLE
OCSP responder configurations

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#24]
Major item that keeps reappearing in questions

Hold here for notes and lessons...

**Comment by lachellel** [comment]
DoD specific - https://blogs.technet.microsoft.com/askpfeplat/2014/01/07/microsoft-pki-ocsp-responder-now-jitc-certified-and-lab-setup-guide/

**Comment by maxwellfunk** [comment]
closing as it is related to #57.  Would need to not only include guidance on configuration of OCSP and SCVP solutions, would also need to provide guidance for relying parties.
