### ISSUE TITLE
PIV credential graphic

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#240]
- Graphic for a PIV credential
- Update the reference on piv guides (optional)

Graphic attributed to: 

- [U.S. Government Accountability Office](https://www.gao.gov/)
- Attribution to GAO for reuse is appreciated

![piv_credential](https://user-images.githubusercontent.com/6501821/54381367-f2c1bb00-4663-11e9-9894-aacbb1b5c952.png)

**Comment by coolmary** [comment]
I really appreciate DHS for given me an Phone PIV with USA Jobs and Common Access Card to login with GSA GWAC, NIST 12 DOT HSPD 12 DOT NIST DISA FPRD PPIRS Ad-hoc DHHS Partners GitHub account

**Comment by sarahdobson** [comment]
Will update graphic with the new consolidated Playbooks site.

**Comment by maxwellfunk** [comment]
Closed per upcoming playbook PIV guide migration.
