### ISSUE TITLE
PIV code signing support

### ISSUE THREAD

**Issue by datocrats-org** [GSA/piv-guides#241]
#### Description of Issue: ####
When packaging MS Access databases (.accdb) and signing VBA modules in MS Access, Excel, and Word, I need the ability to "sign code" with a PIV certificate in order to improve user experience.  Users will be prompted with warnings at various stages such as copying tables from a local database to a network share via UNC link.

#### Details of Issue: ####
I tried each certificate on PIV to Package and Sign an Access database using Save As.  I get a warning message "The certificate is explicitly marked unfit for code signing. Please choose another certificate."

#### References (Docs, Links, Files): ####
None found on Microsoft's help.  Similar info on signing word documents is provided on piv.idmanagement.gov but it does not address code signing.

#### If a New Page or Content is Needed, Expected Outcomes: ####
Code signing tutorial similar to https://piv.idmanagement.gov/userguides/signworddoc-ofr/

#### Link to the Content Page for Contributors: ####
TBD

**Comment by lachellel** [comment]
@datocrats-org 

We do not support code signing with your PIV certificates.  **Code signing** use cases explicitly should use a commercially sourced code signing certificate/key pair.
