### ISSUE TITLE
How to configure Windows web server to only accept PIV certificate

### ISSUE THREAD

**Issue by cyberdude206** [GSA/piv-guides#246]
I want to configure my website to allow users to *only* select the PIV certificate found on their CAC. Currently ActivClient will prompt the user to select either their email cert or their PIV cert.

Currently utilizing Win Server 2012R2, IIS 8.5

**Comment by maxwellfunk** [comment]
Most major browsers populate a credential tile selection screen based off of acceptable key usage (KU) fields and enhanced key usage (EKU) fields.  If digital signature is found in the KU and the client authentication or smart card authentication are found in the EKU then they will be included in the certificate tile selection screen.  

This might be more appropriately addressed by working with your PKI provider to remove client authentication EKU from those email signing certificates.
