### ISSUE TITLE
Credential locks and email client

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#25]
For Outlook: 

https://support.microsoft.com/en-us/kb/2829595

Is this still common and needed in an FAQ?

**Comment by maxwellfunk** [comment]
Ran across the same issue using a PIV with Outlook after having VPNed into a government network.  Ended being prompted for PIN several times, never locked the PIV.  No longer a very common issue since migration to cloud email solutions, and not a known issue for office 2016.
