### ISSUE TITLE
Remove EOL versions (Windows 7 and 2008R2)

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#260]
#### Description of Issue: ####
https://github.com/GSA/piv-guides/blob/staging/_networkconfig/06_tuning.md

#### Details of Issue: ####
Update for new versions
We're all done with these old versions!

#### References (Docs, Links, Files): ####
https://github.com/GSA/piv-guides/blob/staging/_networkconfig/06_tuning.md

**Comment by idmken** [comment]
EOL
Server 2008 (Extended - Jan 2020)
Server 2012 (Oct 2018 - Extended 2023)
Server 2016 (Jan 2022 - Extended 2027)
Server 2019 (Jan 2024 - Extended 2029)
