### ISSUE TITLE
Digitital Signatures During pandemic.

### ISSUE THREAD

**Issue by Allisterc** [GSA/piv-guides#273]
#### Description of Issue: ####
My PIV card expired a few days ago and my building is current closed due to COVID-19.  I cannot get my certificate updated. Is there another option I can use to digitally sign word documents for submission to Federal Register.

**Comment by ryancdickson** [comment]
Have you tried contacting the Office of the Federal Register's support team at ofrtechgroup@gpo.gov?

**Comment by Allisterc** [comment]
I will give send them an email.  Thank you I could not locate any contact information on the website.

**Comment by ryancdickson** [comment]
Closing issue.
