### ISSUE TITLE
Broken link in PIV Usage Guides page

### ISSUE THREAD

**Issue by vinuthomas813** [GSA/piv-guides#287]
#### Description of Issue: ####
When I go to https://piv.idmanagement.gov/identifiers/ and click on the link in "Legacy definition and usage was to support building access control systems as outlined in this document," I get a 404

#### Details of Issue: ####
This text is in the "Considerations" for the "Identifiers" of "Federal Agency Smartcard Number (FASC-N)" - "this document" is a link that points to https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/TIG_SCEPACS_v2.2_0.pdf

#### References (Docs, Links, Files): ####
Link on https://piv.idmanagement.gov/identifiers/ has a broken link to https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/TIG_SCEPACS_v2.2_0.pdf

**Comment by idmken** [comment]
Thank you! @ryancdickson is this the latest version? I found a v2.3 on our share drive.

**Comment by maxwellfunk** [comment]
This issue has been addressed in the new version of the playbooks repository and TIG-SCEPACS v2.3 is the updated version being referenced on the new site.
