### ISSUE TITLE
ActivClient for PIV Enablement

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#36]
Do you need to use ActivClient for PIV enablement of your Windows network?

Using commercial middleware is not a requirement to PIV enable your network devices, desktop applications, and web applications. More recent versions of Microsoft Windows (7+ and Server 2008R2+) can be configured with Active Directory to support PIV authentication for standard and privileged user accounts.

Link to the /piv-guides/networkconfig/

**Comment by lachellel** [comment]
closing - middleware options covered (many options / choices)
