### ISSUE TITLE
PIV enablement of non-Windows systems

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#37]
How do I PIV enable non-Windows based operating systems?

Action: Create new pages for OSX, Linux, Unix and common distributions & versions used across the government.

**Comment by lachellel** [comment]
let's break this into individual issues by OS and purpose (privileged user / servers / etc versus general user and network joined workstations versus users and web app authn)

Then we can collect up the scripts and tools to execute (purpose specific)
