### ISSUE TITLE
Temporary / Interim Access for user with missing PIV

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#38]
How do I configure my networked systems to handle the case where my user doesn't have their PIV?
-Privileged access
-Non-privileged access

Should also create configuration guidance should the agency policy allow for this use case.

**Comment by clstmbrly** [comment]
This Issue relates directly to Issues #[41](https://github.com/GSA/piv-guides/issues/41), "User - Loss of PIV Card," and #[42](https://github.com/GSA/piv-guides/issues/42), "User - Forgotten PIV Card."

**Comment by coolmary** [comment]
I really appreciate your business. I am grateful you have shared your information products and Services with me,have a wonderful,Holidays Cheers.

**Comment by maxwellfunk** [comment]
local policy and risk determination based, closing.
