### ISSUE TITLE
Access for temporary employees / interns

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#39]
How do I configure my systems to allow for short-term employees or interns who are not required to have a PIV and require non-privileged access?

Include that these users should not have privileged access.

**Comment by lachellel** [comment]
I'm going to backlog this.  It's policy specific.

**Comment by maxwellfunk** [comment]
Concur this is policy specific and driven by local risk determinations.  Closing as this is a bit out of scope for PIV guides specifically.
