### ISSUE TITLE
PIV Authentication to Cloud Hosted solutions

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#40]
Is PIV authentication required for accessing cloud hosted solutions?
If your agency users are accessing systems with elevated or privileged access rights, regardless of the hosting solution, you would still need to use a 2-factor hardware authenticator.

**Comment by lachellel** [comment]
need to clarify with the policy references (LOA4)

**Comment by GSAllewell** [comment]
Based on M04-04 ([http://www.whitehouse.gov/omb/memoranda/fy04/m04-04.pdf]) doesn't the LOA requirement depend on the user's role?  For standard users, this could be anything from LOA 1 to 4, depending on the potential impact, right?

**Comment by maxwellfunk** [comment]
Closing due to updated policy and guidance such as SP 800-37, SP 800-53, M-19-17 and the newer Digital Identity Risk Assessment (DIRA) playbook.

Identification and authentications solutions should be based on risk assessments associated with the information being accessed.
