### ISSUE TITLE
User - Loss of PIV Card

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#41]
User FAQ:
Q: What do I do if I lost my PIV card?
A: Contact your agency’s Security Officer if you have lost your credential or believe it has been tampered with. Your current credential will be terminated, and the process for issuing you a new credential will be initiated.

-We may want to add caveats regarding agency specific policies. In theory though, they would take a similar stance on termination.

**Comment by maxwellfunk** [comment]
Instructions for how to deal with lost cards should be included in the PKI subscriber agreement or in localized user security training.
