### ISSUE TITLE
User - Forgotten PIV Card

### ISSUE THREAD

**Issue by maoconnor** [GSA/piv-guides#42]
Q: What do I do if I have misplaced my PIV card but it is recoverable? How do I access the systems required for my job?
A: Contact your agency’s Security Officer if you have temporarily misplace your credential and it is recoverable. Your current credential can be temporarily deactivated and can be reactivated upon recovery. Depending on your agency, their risk assessment process, and your level of access, you may be given temporary access with the strongest authenticator available.

**Comment by ryancdickson** [comment]
Overcome by events (FAQ no longer exists). This would by agency specific.
