### ISSUE TITLE
Cross reference identifiers and network/account linking

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#47]
The table in network/account linking and identifiers should be cross-referenced - 

piv-guides/_networkconfig/4_accounts.md
piv-guides/pages/identifiers.md

The choices to use is recommended (network/accounts) but the engineers should know the reasons and what changes (identifiers)

**Comment by maxwellfunk** [comment]
the account linking identifiers are specific options to AD altsecid mapping, so there is not a 1:1 mapping with the general identifiers.   Engineers should be referencing more detailed specifications (e.g. 800-73) if they will be leveraging or concatenating unique identifiers.
