### ISSUE TITLE
Tuning - network

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#50]
Placeholder for starting to capture the tuning for network auth.

**Comment by lachellel** [comment]
Two settings: 
- Increase the network retrieval timeout setting on your domain:  https://technet.microsoft.com/en-us/library/cc771429(v=ws.11).aspx
- Increase the OCSP setting from the default of "50" to a higher number 
      referenced here under Defining Default Behavior: https://technet.microsoft.com/en-us/library/ee619783(v=ws.10).aspx

**Comment by lachellel** [comment]
patch link again....common question still: 

- https://support.microsoft.com/en-us/kb/2831238

**Comment by djpackham** [comment]
may be worth including the link to the United States Government Configuration Baseline (USGCB)
- https://usgcb.nist.gov/usgcb_content.html
