### ISSUE TITLE
certutils -scinfo

### ISSUE THREAD

**Issue by GSAllewell** [GSA/piv-guides#53]
Native Windows utility to list certificates available on the smart card
**certutil –scinfo.**

You will be prompted for a PIN for each certificate on the card, but it is not required for this operation. You can press ESC if you are prompted for a PIN.

**Comment by rt-smithee** [comment]
Very useful tool.  Available in stock windows, no extra bits to install.  Note this will go out and hit the network for certificate status and such.  It also populates the card's certificates into the windows key store, so after you do a "certutil -scinfo" you can run MMC and  review the certificates.  Also works for TWIC cards.

**Comment by clstmbrly** [comment]
Closing this issue.  This information is now provided as part of the PIV Guides' _Useful Tools_ page.  

- PIV Guides' [Useful Tools](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc732443(v=ws.11)).  (Click on **Useful Tools** at sidebar nav.)
- This page also links to [Microsoft's Certutil article](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc732443(v=ws.11)) that gives a list of Certutil's commands and functions.
