### ISSUE TITLE
suggested correction to page "how to contribute"

### ISSUE THREAD

**Issue by rt-smithee** [GSA/piv-guides#55]
On the "How to Contribute" page in the "How to build a new guide" pagagraph the link to "how to piv enable my logon" does not work (get a 404 error, points to http://gsa.github.io/piv-guides/devconfig/15_network/)

IMO the content on the page is clear.  I think I get the point, I'm merely pointing out the 404 issue.

**Comment by lachellel** [comment]
@rt-smithee thanks!

when we update, the PR will link to this issue

working on updating all the How to Contribute pages for this and other related repos in progress (fpki-guides, all the ficam roadmap, ficam-arch).

**Comment by lachellel** [comment]
I think we fixed this - we changed all the contributing.
