### ISSUE TITLE
Linking network accounts using USAccess reports

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#56]
Purpose: 
- A large portion of agencies need information from the PIV credential certificates (PIV Auth etc) to link the network accounts to the credentials
- Fully automated capabilities are not available or within easy implementation reach for all agencies
- Common question for agencies using USAccess are how to use the existing reports to harvest the information to perform the network account linking automatically (via scripts or other)

Option:
1.  Leverage the Applicant Report (available by agency only)
2.  UUID generation and which fields from the report
3.  UPN generation and which fields from the report

**Comment by lachellel** [comment]
@djpackham 

This is related to the script that pulls data from Applicant Report
Script in private ficam-scripts repo

**Comment by maxwellfunk** [comment]
This could be extended to exports of certificate reports from CAs outside of a CMS.  Would need to document/survey other participating agencies to determine their workflows. 

Do they create the AD account or email address first and then populate a CMS or other certificate application or vice versa?
