### ISSUE TITLE
pvicertchains -> federal pki infrastructure data

### ISSUE THREAD

**Issue by rt-smithee** [GSA/piv-guides#63]
#### Description of Issue:

pivcertchains contains the link http://fpki-graph.fpki-lab.gov/ to a graphical representation of the federal pki.  issue:  it's not text, it's not searchable.
#### Details of Issue:

when relying parties call on technical support teams inquiring about intermediate CA status it would be helpful if one could search for a given CA name in a text file or spreadsheet or some other machine readable form.
#### References (Docs, Links, Files):

 http://fpki-graph.fpki-lab.gov/ as referred to in page now
#### If a New Page or Content is Needed, Expected Outcomes:

suggest add text downloadable file link in addition to current information so it's searchable.

**Comment by weirdscience** [comment]
Reports in csv and html are available on https://fpki-graph.fpki-lab.gov/crawler/
