### ISSUE TITLE
Removal of PIV Card Behavior

### ISSUE THREAD

**Issue by bkynaston** [GSA/piv-guides#78]
#### Description of Issue: ####
Discuss guidance and lessons learned for most effective behavior of workstations upon removal of PIV card from reader. Please reference attached draft guidance that resulted from a related Tiger Team within the federal Logical Access Working Group (LAWG).

#### Details of Issue: ####
If a policy of "must lock workstation behavior" upon card removal:
- Increased number of users walking around building without PIV card (it is still stuck in reader)
- Difficulty supporting PIV logical access to multiple workstations at same time
- Unattended PIV cards left in reader

Mitigation:
- Do not lock upon card removal, rely on user lock and screen timeout for unattended workstation security 

#### References (Docs, Links, Files): ####
- Please reply with ideas, considerations, links to existing published/draft guidance to consider

#### Link to the Content Page for Contributors: ####
[USGCB Smartcard Removal Recommendation_LAWG Review Draft_20130503.pdf](https://github.com/GSA/piv-guides/files/699959/USGCB.Smartcard.Removal.Recommendation_LAWG.Review.Draft_20130503.pdf)

**Comment by lachellel** [comment]
@bkynaston

Great question, and I marked as FAQ - it's common. 

- In April 2016, an update to the US Government Configuration Baseline was approved and finalized and published.  It covered the Smartcard Removal Behavior, specific to concerns raised by agencies in a gov writeup.  Snip from the announcement at the time: 

```
For more details, see item **13** in the change log for the USGCB content at http://usgcb.nist.gov/
usgcb/content/scap/changelog.txt under the changes for 2/10/2015 which states:
13.Change Request: update the “Interactive Logon: Smartcard removal behavior” to
“No Action.”
```

This allows a choice to be made.  If you choice to not lock on smartcard removal, your mitigation is aligned with practices for session and workstation lock. 

We should add to an FAQ.

**Comment by bkynaston** [comment]
Fantastic comment - and updates my attached guidance. Thanks Lachelle!!

**Comment by clstmbrly** [comment]
Closing this Issue - appears resolved.

**Comment by bkynaston** [comment]
Yes thank you! 

-- 
Brent Kynaston
Solutions Architect
TriVir, LLC
c: 703-772-8689
e: bkynaston@trivir.com

www.trivir.com
www.idmunit.org
