### ISSUE TITLE
Enable User Name Hints - 2012 

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-guides#81]
#### Description of Issue: ####
2008R2:

- Computer Configuration -> Policies-> Administrative Templates -> Windows Components, and then expand Smart Card.
- Select Allow user name hint

2012: 
- Computer Configuration ->  Administrative Templates -> Windows Components, and then expand Smart Card.
- Select Allow user name hint

#### Details of Issue: ####
Note change in where...add to the list 
piv-guides/_networkconfig/4_accounts.md

#### References (Docs, Links, Files): ####
@GSAllewell notes

**Comment by djpackham** [comment]
Just to clarify, there is already 2008R2 configuration presently shown at 

- https://github.com/GSA/piv-guides/blob/staging/_networkconfig/4_accounts.md

 Need to update with 2012 configuration as well.
