### ISSUE TITLE
PIV Guides Link update

### ISSUE THREAD

**Issue by Protiviti-JSargent** [GSA/piv-guides#83]
#### Description of Issue: ####
Updated link needed in the contribute.md file.

#### Details of Issue: ####
In the section titled "How to Build a New Guide", the playbook directs new contributors to an example playbook titled 'How do I PIV enable my network logon?' and provides a link to the following url to use as a guide and template for creating a new playbook: https://github.com/GSA/piv-guides/blob/staging/pages/%7B%7B%20site.baseurl%20%7D%7D/devconfig/15_network.

The link is dead and there does not seem to be a 15_network file in the devconfig folder.  If this file has been moved, the link should be updated with the new location.  If the page has been removed, the how to contribute guide should be updated to reference a different document to use as a template.

#### References (Docs, Links, Files): ####
https://github.com/GSA/piv-guides/blob/staging/pages/contribute.md

#### Link to the Content Page for Contributors: ####
https://github.com/GSA/piv-guides/blob/staging/pages/contribute.md

**Comment by lachellel** [comment]
Agree, I removed all extraneous files when applying new style sheets and cleaning all the existing markdown and references.  

Suggesting another approach:
- The entire Contributing needs to be rewritten.  It's wordy, and was pulled from the architecture git hub repo.
